### ISSUE TITLE
Bug: User tracking without consent

### ISSUE THREAD

**Issue by MMeent** [minvws/nl-covid19-data-dashboard#957]
### Describe the bug, issue or concern

Currently, some PII is sent to a piwik instance that is hosted by Microsoft when loading any page (e.g. my public IP, that is PII). Please disable this integration for users that have not given consent to user tracking.

### To Reproduce
1. Go to coronadashboard.government.nl
2. Note that it includes links to statistiek.rijksoverheid.nl/piwik.php
3. Also note that the IP of statistiek.rijksoverheid.nl ( 13.94.196.189 ) is owned by Microsoft (according to the ARIN whois database)

### Expected behavior
No requests are made to external tracking systems without explicit user consent.

### Screenshots
n/a

**Desktop (please complete the following information):**
 - OS: Debian 10.9
 - Browser: FireFox
 - Version 83.0

### Additional context
It is my understanding that users cannot be tracked unless they have given their informed consent, or one of the other reasons specified by the GDPR. Unless you are basing your data gathering on those other pillars (in which case, please tell me so), explicit informed consent is required from the user before data gathering starts.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
I've reached out to the department that manages the Piwik-setup to be able to give you a precise answer on this. Will update the comment once that's in.

**Comment by VWSCoronaDashboard7** [comment]
Sorry for the delay in this. I have confirmed that we _do not store_ your IP adres in Piwik but anonymise this in a similar manner as mentioned in the the guidelines for Google Analytics by the Autoriteit Persoonsgegevens. So for an IPv4 the last octet is zeroed and for IPv6 the last two octets are removed. As such we believe this complies with all applicable legislation. Therefore I'm closing this report. Feel free to reach out if you have additional questions.

**Comment by MMeent** [comment]
> So [...] for IPv6 the last two octets are removed

In technical terms, do you store the `::/112` (=`/128` - 16 bits) or the `::/48` (= `/64` - 16 bits)? A `::/112` is still reasonably unique for a person (`::/64` is the most specific publicly routable address size, and often assigned to the consumer's router. For example, [Ziggo provides each of it's customers' routers with a `/58`](https://community.ziggo.nl/internetverbinding-102/een-beknopte-uitleg-van-ipv6-2989) ). 

> Feel free to reach out if you have additional questions.

It also seems like there is some user identifier that is stored in cookies and communicated to Piwik. This is always communicated with the IP, so that would also make that PII. Do you have a link to where you provide the information as required per Art. 13 of the GDPR?
